In [1]:
from pathlib import Path

dataset_path = Path("./Dataset/Aircraft_Fuselage_DET2023/aircraft_fuselage_yolo")
labels = sorted(dataset_path.rglob("*labels_full/*.txt"))[:-1]  # all data in 'labels'
labels[-1]

PosixPath('Dataset/Aircraft_Fuselage_DET2023/aircraft_fuselage_yolo/labels_full/414.txt')

In [2]:
import yaml

yaml_file = "AFDET_dataset.yaml"  # your data YAML with data directories and names dictionary
with open(yaml_file, encoding="utf8") as y:
    classes = yaml.safe_load(y)["names"]
cls_idx = sorted(classes.keys())
cls_idx

[0, 1, 2, 3]

In [3]:
import pandas as pd

index = [label.stem for label in labels]  # uses base filename as ID (no extension)
labels_df = pd.DataFrame([], columns=cls_idx, index=index)

In [4]:
from collections import Counter

for label in labels:
    lbl_counter = Counter()

    with open(label) as lf:
        lines = lf.readlines()

    for line in lines:
        # classes for YOLO label uses integer at first position of each line
        lbl_counter[int(line.split(" ", 1)[0])] += 1

    labels_df.loc[label.stem] = lbl_counter

labels_df = labels_df.fillna(0.0)  # replace `nan` values with `0.0`

In [5]:
labels_df['y'] = labels_df.index.to_series().apply(lambda x: x.split('_')[0])
labels_df

       0    1    2    3    y
001  2.0  0.0  0.0  0.0  001
002  5.0  0.0  0.0  0.0  002
003  2.0  0.0  0.0  0.0  003
004  6.0  0.0  0.0  0.0  004
005  0.0  1.0  0.0  0.0  005
..   ...  ...  ...  ...  ...
410  0.0  0.0  0.0  1.0  410
411  1.0  0.0  0.0  0.0  411
412  1.0  0.0  0.0  0.0  412
413  1.0  0.0  0.0  0.0  413
414  2.0  0.0  0.0  0.0  414

[389 rows x 5 columns]

In [6]:
import random

from sklearn.model_selection import KFold, GroupKFold

random.seed(0)  # for reproducibility
ksplit = 5
kf = GroupKFold(n_splits=ksplit)  # setting random_state for repeatable results

# shuffle labels_df before splitting
# labels_df = labels_df.sample(frac=1, random_state=0).reset_index(drop=True)
# labels_df_suffled = labels_df

kfolds = list(kf.split(labels_df, groups=labels_df['y']))
len(kfolds)
# kfolds[0]

5

In [7]:
labels_df.iloc[kfolds[1][0]].index # train indices of fold 1

Index(['001', '002', '004', '005', '006', '007', '009', '010', '011', '012',
       ...
       '403', '404', '405', '406', '408', '409', '410', '411', '413', '414'],
      dtype='object', length=311)

In [8]:
folds = [f"split_{n}" for n in range(1, ksplit + 1)]
folds_df = pd.DataFrame(index=index, columns=folds)
folds_df

    split_1 split_2 split_3 split_4 split_5
001     NaN     NaN     NaN     NaN     NaN
002     NaN     NaN     NaN     NaN     NaN
003     NaN     NaN     NaN     NaN     NaN
004     NaN     NaN     NaN     NaN     NaN
005     NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...
410     NaN     NaN     NaN     NaN     NaN
411     NaN     NaN     NaN     NaN     NaN
412     NaN     NaN     NaN     NaN     NaN
413     NaN     NaN     NaN     NaN     NaN
414     NaN     NaN     NaN     NaN     NaN

[389 rows x 5 columns]

In [9]:

for i, (train, val) in enumerate(kfolds, start=1):
    folds_df[f"split_{i}"].loc[labels_df.iloc[train].index] = "train"
    folds_df[f"split_{i}"].loc[labels_df.iloc[val].index] = "val"

In [10]:
folds
del labels_df['y']
labels_df

       0    1    2    3
001  2.0  0.0  0.0  0.0
002  5.0  0.0  0.0  0.0
003  2.0  0.0  0.0  0.0
004  6.0  0.0  0.0  0.0
005  0.0  1.0  0.0  0.0
..   ...  ...  ...  ...
410  0.0  0.0  0.0  1.0
411  1.0  0.0  0.0  0.0
412  1.0  0.0  0.0  0.0
413  1.0  0.0  0.0  0.0
414  2.0  0.0  0.0  0.0

[389 rows x 4 columns]

In [11]:
fold_lbl_distrb = pd.DataFrame(index=folds, columns=cls_idx)
fold_lbl_distrb

           0    1    2    3
split_1  NaN  NaN  NaN  NaN
split_2  NaN  NaN  NaN  NaN
split_3  NaN  NaN  NaN  NaN
split_4  NaN  NaN  NaN  NaN
split_5  NaN  NaN  NaN  NaN

In [12]:

for n, (train_indices, val_indices) in enumerate(kfolds, start=1):
    train_totals = labels_df.iloc[train_indices].sum()
    val_totals = labels_df.iloc[val_indices].sum()

    # To avoid division by zero, we add a small value (1E-7) to the denominator
    ratio = val_totals / (train_totals + 1e-7)
    fold_lbl_distrb.loc[f"split_{n}"] = ratio

In [13]:
fold_lbl_distrb

                0         1         2         3
split_1  0.228571  0.287037  0.329268  0.094595
split_2  0.280851  0.219298  0.197802  0.472727
split_3  0.291845  0.188034  0.313253  0.327869
split_4  0.175781  0.252252  0.211111  0.327869
split_5  0.280851  0.311321  0.211111  0.109589

In [14]:
import datetime

supported_extensions = [".jpg", ".jpeg", ".png"]

# Initialize an empty list to store image file paths
images = []

# Loop through supported extensions and gather image files
for ext in supported_extensions:
    images.extend(sorted((dataset_path / "images_full").rglob(f"*{ext}")))

# Create the necessary directories and dataset YAML files
save_path = Path(dataset_path / f"{datetime.date.today().isoformat()}_{ksplit}-Fold_Cross-val")
save_path.mkdir(parents=True, exist_ok=True)
ds_yamls = []

for split in folds_df.columns:
    # Create directories
    split_dir = save_path / split
    split_dir.mkdir(parents=True, exist_ok=True)
    (split_dir / "train" / "images").mkdir(parents=True, exist_ok=True)
    (split_dir / "train" / "labels").mkdir(parents=True, exist_ok=True)
    (split_dir / "val" / "images").mkdir(parents=True, exist_ok=True)
    (split_dir / "val" / "labels").mkdir(parents=True, exist_ok=True)

    # Create dataset YAML files
    dataset_yaml = split_dir / f"{split}_dataset.yaml"
    ds_yamls.append(dataset_yaml)

    with open(dataset_yaml, "w") as ds_y:
        yaml.safe_dump(
            {
                "path": split_dir.as_posix(),
                "train": "train",
                "val": "val",
                "names": classes,
            },
            ds_y,
        )

In [16]:
ds_yamls

[PosixPath('Dataset/Aircraft_Fuselage_DET2023/aircraft_fuselage_yolo/2026-02-02_5-Fold_Cross-val/split_1/split_1_dataset.yaml'),
 PosixPath('Dataset/Aircraft_Fuselage_DET2023/aircraft_fuselage_yolo/2026-02-02_5-Fold_Cross-val/split_2/split_2_dataset.yaml'),
 PosixPath('Dataset/Aircraft_Fuselage_DET2023/aircraft_fuselage_yolo/2026-02-02_5-Fold_Cross-val/split_3/split_3_dataset.yaml'),
 PosixPath('Dataset/Aircraft_Fuselage_DET2023/aircraft_fuselage_yolo/2026-02-02_5-Fold_Cross-val/split_4/split_4_dataset.yaml'),
 PosixPath('Dataset/Aircraft_Fuselage_DET2023/aircraft_fuselage_yolo/2026-02-02_5-Fold_Cross-val/split_5/split_5_dataset.yaml')]

In [17]:
folds_df

    split_1 split_2 split_3 split_4 split_5
001   train   train   train     val   train
002     val   train   train   train   train
003   train     val   train   train   train
004   train   train     val   train   train
005   train   train   train     val   train
..      ...     ...     ...     ...     ...
410   train   train   train   train     val
411     val   train   train   train   train
412   train     val   train   train   train
413     val   train   train   train   train
414     val   train   train   train   train

[389 rows x 5 columns]

In [18]:
import shutil

from tqdm import tqdm

for image, label in tqdm(zip(images, labels), total=len(images), desc="Copying files"):
    for split, k_split in folds_df.loc[image.stem].items():
        # Destination directory
        img_to_path = save_path / split / k_split / "images"
        lbl_to_path = save_path / split / k_split / "labels"

        # Copy image and label files to new directory (SamefileError if file already exists)
        shutil.copy(image, img_to_path / image.name)
        shutil.copy(label, lbl_to_path / label.name)

Copying files: 100%|██████████| 389/389 [00:00<00:00, 912.24it/s]

In [19]:
folds_df.to_csv(save_path / "kfold_datasplit.csv")
fold_lbl_distrb.to_csv(save_path / "kfold_label_distribution.csv")

In [ ]:
# scratch data can be taken from 
# https://github.com/Hacksutates/paint-defect-detection/blob/main/dataset22/data.yaml